# Generated by Django 4.0.3 on 2022-11-20 00:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='bio_y_cor_report',
            field=models.FileField(null=True, upload_to='report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='quimico_report',
            field=models.FileField(null=True, upload_to='report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2022)]),
        ),
    ]
