# Generated by Django 4.0.3 on 2022-11-20 00:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_report_bio_y_cor_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ord_y_rec_report',
            field=models.FileField(null=True, upload_to='report'),
        ),
        migrations.AlterField(
            model_name='report',
            name='year',
            field=models.IntegerField(default=2015, validators=[django.core.validators.MinValueValidator(2015), django.core.validators.MaxValueValidator(2022)]),
            preserve_default=False,
        ),
    ]
