# Generated by Django 4.0.3 on 2022-11-20 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_report_ord_y_rec_report_alter_report_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='bio_y_cor_report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='ord_y_rec_report',
        ),
        migrations.RemoveField(
            model_name='report',
            name='quimico_report',
        ),
        migrations.AddField(
            model_name='report',
            name='report',
            field=models.FileField(null=True, upload_to='report'),
        ),
    ]
